services:
  # Название нашего сервиса
  chart-api:
    # Указываем, что нужно собирать образ из текущей директории
    build: .
    # Даем контейнеру имя для удобства
    container_name: chart-api
    # Пробрасываем переменные окружения из файла .env в контейнер
    env_file:
      - .env
    # Пробрасываем порты: 8000 порт на хост-машине (сервере 'ved')
    # будет связан с 8000 портом внутри контейнера, где работает FastAPI
    ports:
      - "8000:8000"
    # Монтируем текущую папку с кодом (app) внутрь контейнера.
    # Это ключевая фича для разработки: любые изменения в коде на хосте
    # будут мгновенно отражаться внутри контейнера без его пересборки.
    volumes:
      - .:/app
    # Команда, которая будет запущена при старте контейнера.
    # uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # --host 0.0.0.0: Слушать на всех сетевых интерфейсах внутри контейнера.
    # --reload: Uvicorn будет автоматически перезапускаться при изменении кода. Идеально для разработки.
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]